# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  deploy-cmd:
    parameters: 
      environment:
        type: string
        default: dev
    steps:
      - run:
          name: Application Deployment
          command: echo Deploy application to Kubernetes Cluster with Argo in << parameters.environment >> environment
    
branch_not_main_filter: &run_when_branch_not_main
  when:
    not:
      matches:
        pattern: "^main$"
        value: << pipeline.git.branch >>

branch_is_main_filter: &run_when_branch_is_main
  when:
    matches:
      pattern: "^main$"
      value: << pipeline.git.branch >>        


orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  static-code-analysis:
    docker:
      - image: cimg/openjdk:18.0.2
    
    working_directory: /mnt/ramdisk

    steps:
      - checkout
      - run:
          name: Code analysis
          command: |
            cd apps/demo && ./gradlew clean detekt
      - run:
          name: Sync with sonar
          command: |
            cd apps/demo
            ls -la build/reports/detekt
            ./gradlew sonarqube -i
          when: always
  unit-test: 
    docker:
      - image: cimg/openjdk:18.0.2

    working_directory: /mnt/ramdisk

    steps:
      - checkout
      - run: 
          name: "Run unit tests and publish reports"
          command: |
            mkdir -p ~/test-results/reports
            cd apps/demo && ./gradlew clean unitTest jacocoTestReport 
            ./gradlew sonarqube -i
            cp build/test-results/unitTest/*.xml ~/test-results/reports
            ls -la build/testReports/test
      - store_test_results:
          path: ~/test-results

  publish-release:
    docker:
      - image: timbru31/java-node:17-alpine-jdk-18
        environment:
          GITHUB_TOKEN: $GITHUB_TOKEN
    steps:
      - checkout
      - run:
          name: "Publish release"
          command: |
            ./gradlew createRelease

  build:
    docker:
      - image: cimg/openjdk:18.0.2
        environment:
          SONAR_TOKEN: $SONAR_TOKEN
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: pwd && ls -la
      - run: gradle --version
      - run: |
          cd apps/demo
          ./gradlew clean build
          docker build .
  deploy:
    parameters:
      environment:
        type: string
        default: dev
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - deploy-cmd:
          environment: << parameters.environment >>

workflows:
  quality_assurance:
    <<: *run_when_branch_not_main
    jobs:
      - static-code-analysis:
          context: SonarCloud
      - unit-test:
          context: SonarCloud
      - gradle/test:
          name: component-test
          app_src_directory: "./apps/demo/"
          test_results_path: "./apps/demo/build/test-results/componentTest"
          reports_path: "./apps/demo/build/reports"
          test_command: "componentTest"
  build_and_deploy:
    <<: *run_when_branch_is_main
    jobs:
      - publish-release:
          context: SonarCloud
      - static-code-analysis:
          context: SonarCloud
      - unit-test:
          context: SonarCloud
      - build:
          requires:
            - unit-test
      - deploy:
          environment: prod
          requires:
           - publish-release
