# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

workflows:
  feature-branch:
    jobs:
      - gradle/test:
          name: "Unit Test"
          app_src_directory: "./apps/demo/"
          test_results_path: "./apps/demo/build/test-results/"
          reports_path: "./apps/demo/build/reports"
          test_command: "unitTest"