# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  deploy-cmd:
    parameters: 
      environment:
        type: string
        default: dev
    steps:
      - run:
          name: Application Deployment
          command: echo Deploy application to Kubernetes Cluster with Argo in << parameters.environment >> environment
    

only_dev: &only_dev
  filters:
    branches:
      only: [/^feature.*/, /^hotfix.*/]
orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: pwd && ls -la
      - run: gradle --version
      - run: cd apps/demo && ./gradlew clean build -x test && docker build .
      - run: docker image
  deploy:
    parameters:
      environment:
        type: string
        default: dev
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - deploy-cmd:
          environment: << parameters.environment >>
    
workflows:
  deploy-to-dev:
    jobs:
      - build:
          requires:
            - component-test
            - unit-test
      - gradle/test:
          name: unit-test
          app_src_directory: "./apps/demo/"
          test_results_path: "./apps/demo/build/test-results/test"
          reports_path: "./apps/demo/build/reports"
          test_command: "unitTest"
          <<: *only_dev
      - gradle/test:
          name: component-test
          app_src_directory: "./apps/demo/"
          test_results_path: "./apps/demo/build/test-results/componentTest"
          reports_path: "./apps/demo/build/reports"
          test_command: "componentTest"
      - deploy:
          name: dev-deploy
  deploy-to-prod:
    jobs:
      - build:
          filters:
            branches:
              only:
               - main
      - deploy:
          name: deploy
          environment: prod
          requires:
           - build