# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0


jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: pwd && ls -la
      - run: gradle --version
      - run: cd apps/demo && ./gradlew clean build -x test && docker build .
      - run: docker image
  dev-deploy:
    name: deploy
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run: echo "Deploy container to Kubernete Cluster with Argo in Dev Environment"
  deploy:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run: echo "Deploy container to Kubernete Cluster with Argo"
    
workflows:
  deploy-to-dev:
    jobs:
      - build:
          requires:
            - component-test
            - unit-test
      - gradle/test:
          name: unit-test
          app_src_directory: "./apps/demo/"
          test_results_path: "./apps/demo/build/test-results/test"
          reports_path: "./apps/demo/build/reports"
          test_command: "unitTest"
      - gradle/test:
          name: component-test
          app_src_directory: "./apps/demo/"
          test_results_path: "./apps/demo/build/test-results/componentTest"
          reports_path: "./apps/demo/build/reports"
          test_command: "componentTest"
      - dev-deploy:
          requires:
            - build
  deploy-to-prod:
    jobs:
      - build:
          filters:
            branches:
              only:
               - main
      - deploy:
          filters:
            branches:
              only:
               - main
          requires:
           - build


